// Auto-generated from merchants_list.csv
// 763 merchants — sorted alphabetically as delivered.
export const MERCHANTS = [
  '24S',
  'AIRE Ancient Baths Chicago',
  'AIRE New York \u00b7 Tribeca',
  'AIRE New York \u00b7 Upper East Side',
  'ALLEGIANT AIR',
  'ALLEGNT AIR, LLC',
  'AO Everyplate AU',
  'ASBeauty',
  'AT Hellofresh AT',
  'AU Dinnerly',
  'AU Hellofresh AU',
  'AU Marley Spoon',
  'AccentGroup',
  'Accrue',
  'Acemart',
  'Activated Events',
  'Adidas Argentina',
  'Adidas Brazil',
  'Adidas Chile',
  'Adidas EU',
  'Adidas Mexico',
  'Adidas Peru',
  'Adidas US',
  'Ads Studio',
  'Affirm Canada',
  'Affirm, Inc.',
  'Allegiant Air Travel',
  'Alphacomm ACS',
  'Alphacomm B2B',
  'Alphacomm B2C',
  'Alphacomm Mi Pay',
  'Alphacomm RLN',
  'Alphacomm Sure',
  'Alphacomm Tesco Mobile',
  'Alphacomm White Calling',
  'Alton Towers Resort - Tickets',
  'Altra',
  'Anaclair',
  'Arbor - AC Phoenix Downtown',
  'Arbor - Aloft Glendale',
  'Arbor - Courtyard Indianapolis Northwest',
  'Arbor - Hampton Inn Norwood',
  'Arbor - Hampton/Homewood Chicago',
  'Arbor - Hilton Garden Inn - San Leandro',
  'Arbor - Homewood Suites Somerset',
  'Arbor - Hotel Phillips',
  'Arbor - Residence Inn Mt. Olive',
  'Arbor - SHS Arcadia',
  'Arbor - Springhill Suites Mall of America',
  'Arbor - Tru by Hilton Troy Detroit',
  'Arbor- HGI ANN ARBOR',
  'Arbor- HGI ARCADIA',
  'Arbor- HGI BURLINGTON',
  'Arbor- HGI ROSEVILLE',
  'Arbor- HI MOA',
  'Arbor- HIX NOLA',
  'Arbor- HWS WALLINGFORD',
  'Arbor- HYATT PLACE IOWA CITY',
  'Arbor- Home2 Suites by Hilton Champaign-Urbana',
  'Arbor- INDIGO',
  'Arbor- RI ROCKY HILL',
  'Arbor- RI SALT LAKE',
  'Arbor- TPS ANN ARBOR',
  'Arbor- TPS Glendale',
  'Arcteryx',
  'Aritzia CA',
  'Aritzia US',
  'Aura Luxor Jewelry_#_9be88a1',
  'Auranaturals',
  'AutoDS - Create UGC',
  'AutoDS - Drop Shipping',
  'AutoDS - Full Order Fulfillment',
  'AutoDs - Build Your Store',
  'AvantStay',
  'Aviagames',
  'BE Hellofresh BE',
  'Babyboo Fashion',
  'Baccarat',
  'BackMarket',
  'Badiee Stylez_#_d376101',
  'Baywood - Doubletree by Hilton Sterling Dulles Airport',
  'Baywood - Fairfield Inn & Suites Alexandria West Mark Center',
  'Baywood - Fairfield Inn Metairie',
  'Baywood - Hampton Inn & Suites Falls Church',
  'Baywood - Hampton Inn French Market',
  'Baywood - Hampton Inn Lawrenceville',
  'Baywood - Holiday Inn Express & Suites Alexandria Fort Belvoir',
  'Baywood - Home 2 Suites Kenner',
  'Baywood - Home2 Suites Asheville Biltmore Village',
  'Baywood - Home2 Suites Charlottesville Downtown',
  'Baywood - Home2 Suites Marysville',
  'Baywood - Home2 Suites Minneapolis Mall of America',
  'Baywood - Home2 Suites Polaris',
  'Baywood - Homewood Suites Alexandria Pentagon South',
  "Baywood - Homewood Suites by Hilton Dulles Int'l Airport",
  'Baywood - Residence Inn Elmwood',
  'Baywood - Tru Minneapolis Mall of America',
  'Baywood- Home2 Suites by Hilton Lakeland North I4',
  'Beauty Counter',
  'Bellhop',
  'Ben Moss',
  'Best Buy Marketplace',
  'Best Buy Recurring',
  'BevMo',
  'BeyondBody',
  'Bezel',
  'Bilt Collection',
  'Bilt Dining',
  'Bilt Experiences',
  'Bilt Fitness',
  'Bilt Grocery',
  'Bilt Travel',
  'BingLee',
  'Bingo Loco',
  'Biovitals',
  'BistroMD',
  'Bitiba',
  'Blunstone',
  'Boataround',
  'Bodega',
  'BodyByRaven',
  'Boohoo',
  'Brilliant Earth',
  'Brooklinen',
  'Brytme',
  'Bulgoire',
  'ButcherBox',
  'CA Hellofresh CA',
  'CF Factor75 CA',
  'CG Greenchef US',
  'CH Hellofresh CH',
  'CHARLOTTE AIRPORT HILTON 275',
  'CK Chefsplate CA',
  'Car Rental Gateway',
  'CardCash',
  'Carparts.com',
  'CertifiedFasting',
  'Charm Jewelry Ltd.',
  'Checkoutera',
  'Cherry',
  'Chessington World of Adventures - Tickets',
  'Chewy',
  'Chicago Symphony Orchestra - Ticketing',
  'Chicago Symphony Orchestra - Web',
  'Christian Dior Perfums CA',
  'Chrome Hearts',
  'Chumba Casino',
  'Circa Sports Colorado',
  'Circa Sports Illinois',
  'Circa Sports Kentucky',
  'Citizen Watch',
  'Civitatis',
  'Clarins.com',
  'Clerri',
  'Coach',
  'CoinMaster Direct US',
  'Coinflow',
  'Coingate',
  'Constant Contact',
  'Corsair',
  'Craft Gin Club',
  'CrazySales',
  'CrealityCA',
  'CrealityUS',
  'Crescent',
  'DE Hellofresh DE',
  'DE Marley Spoon',
  'DJI Hasselblad_#_5cbd768',
  'DK Hellofresh DK',
  'Deadstock',
  'Deckers',
  'Deliveroo',
  'DenimTears',
  'Dennis Kirk',
  'Dickies',
  'Doordash AU',
  'Dossier',
  'Driffle',
  'Dyson',
  'EL AL',
  'ER Everyplate US',
  'ES Hellofresh ES',
  'Easol',
  'Edisons & Mytopia',
  'El Dorado',
  'Elgato',
  'Eneba',
  'Envision Festival',
  'Escape Records',
  'Etihad',
  'FJ Factor75 US',
  'FR Hellofresh FR',
  'FamilyIsland',
  'Fast Track Health Insurance LLC',
  'FentyBeauty',
  'Field of Vision',
  'FindANeighborhood',
  'Fiverr',
  'Flashparking',
  'FlexCharge',
  'Full Compass',
  'G-Star Raw',
  'G2A -Forter',
  'G2A.COM',
  'GB Hellofresh GB',
  'GN Greenchef GB',
  'Gametime',
  'Get Your Guide',
  'Global Poker',
  'Global-E - SMB',
  'Global-e',
  'Glopal',
  'Glossier',
  'Glossier UK',
  'GoPuff',
  'GrubHub',
  'Guardio',
  'HEI - Astor Crowne Plaza New Orleans',
  'HEI - Chateau Elan, Atlanta',
  'HEI - Courtland Grand Hotel',
  'HEI - Courtyard Manhattan Midtown East',
  'HEI - Crescent Court Dallas',
  'HEI - EVEN Brooklyn',
  'HEI - EVEN Rockville',
  'HEI - Elements Basalt',
  'HEI - Hotel Colonnade Coral Gables',
  'HEI - Hotel at Avalon',
  'HEI - Hyatt Regency Sonoma Wine Country',
  'HEI - Kartrite Resort & Indoor Waterpark',
  'HEI - Kimpton Goodland Fort Lauderdale',
  'HEI - Kimpton Sylvan Hotel',
  'HEI - Marriott Costa Masa',
  'HEI - SpringHill Suites Pittsburgh Bakery Sq',
  'HEI - Westcherster Marriott',
  'HEI - Westin Baltimore Washington Airport',
  'HEI - Westin Grand Central',
  'HEI- Aloft Miami',
  'HEI- Aloft Tampa Downtown',
  'HEI- Doubletree Pittsburgh-Cranberry',
  'HEI- Elements Orlando',
  'HEI- Embassy Suites Atlantic Station',
  'HEI- Embassy Suites San Diego Bay Downtown',
  'HEI- Embassy Suites Tyson Center',
  'HEI- Embassy Suites Waltham',
  'HEI- Home2Suites Alpharetta',
  'HEI- Hotel Chicago',
  'HEI- Hyatt Jersey City',
  'HEI- Hyatt Place Albany',
  'HEI- Hyatt Regency Boston Harbor',
  'HEI- Hyatt Regency Dulles Airport',
  'HEI- Hyatt Regency Greenwich',
  'HEI- Le Meridien Dallas Stoneleigh',
  'HEI- Marriott Baltimore Inner Harbor at Camden',
  'HEI- Marriott La Jolla San Diego',
  'HEI- Marriott San Ramon',
  'HEI- Renaissance Times Square',
  'HEI- Residence Inn Birmingham',
  'HEI- Revere Hotel Boston Common',
  'HEI- Salt Lake Marriott Downtown at City Creek',
  'HEI- Sheraton Parsippany Hotel',
  'HEI- Sheraton Stonebriar Hotel',
  'HEI- The Jay Hotel',
  'HEI- The Kimpton Brice Hotel',
  'HEI- The Laura',
  'HEI- The Madison Hotel',
  'HEI- The Whaler',
  'HEI- The Whitley',
  'HEI- Westin Atlanta Perimeter',
  'HEI- Westin Beach Resort Ft Lauderdale',
  'HEI- Westin Buckhead',
  'HEI- Westin Cleveland',
  'HEI- Westin Minneapolis',
  'HEI- Westin Pasadena',
  'HEI- Westin Reston Heights',
  'HEI- Westin Waltham',
  'HEI- Westshore Grand Tampa',
  'HEI- Wyndham Bonnet Creek',
  'HEI- Wyndham San Diego Bayside',
  'HUGO BOSS AG',
  'Haigaote',
  'Harry Rosen',
  'Healthy Directions',
  'Hismile',
  'Hismile AU',
  'Hismile CA',
  'Hismile EU',
  'Hismile INT',
  'Hismile UK',
  'Hismile US',
  'Holiday Inn Club Vacations',
  'Home Chef',
  'Hostinger',
  'Hostinger DLocal',
  'Hotel Planner',
  'Hotels In America',
  'House',
  'Hyatt - ALBOB',
  'Hyatt - ATLZB',
  'Hyatt - ATLZG',
  'Hyatt - ATLZS',
  'Hyatt - ATLZT',
  'Hyatt - AUSOB',
  'Hyatt - BNAZH',
  'Hyatt - BOSZS',
  'Hyatt - BWIRB',
  'Hyatt - CHIPH',
  'Hyatt - CLTXD',
  'Hyatt - CLTZT',
  'Hyatt - CMHZD',
  'Hyatt - COSZC',
  'Hyatt - DETZU',
  'Hyatt - DFWZI',
  'Hyatt - DFWZN',
  'Hyatt - ELPZA',
  'Hyatt - GNVZG',
  'Hyatt - IADZN',
  'Hyatt - IADZS',
  'Hyatt - INDZA',
  'Hyatt - LGBRL',
  'Hyatt - LGBRP',
  'Hyatt - MKCZC',
  'Hyatt - MSNZD',
  'Hyatt - MSYXD',
  'Hyatt - NYCGH',
  'Hyatt - NYCPH',
  'Hyatt - OAKXE',
  'Hyatt - OAKXS',
  'Hyatt - ORLZA',
  'Hyatt - PHLZM',
  'Hyatt - PHXRP',
  'Hyatt - PHXZA',
  'Hyatt - SANXS',
  'Hyatt - SATZR',
  'Hyatt - SFOZF',
  'Hyatt - SJCXC',
  'Hyatt - SJCXJ',
  'Hyatt - SNARI',
  'Hyatt - SNAXC',
  'Hyatt - SNAXI',
  'Hyatt - TUSOB',
  'IE Hellofresh IE',
  'IT Hellofresh IT',
  'IXL',
  'In Network Rent',
  'Incogni',
  'Incruises',
  'Inditex',
  'JD Canada',
  'Jackery',
  'Jetabroad',
  'Jomashop',
  'Journeys',
  'K12',
  'KN Thepetstable US',
  'Kate Spade',
  'Keen Footwear',
  'Keto Cycle',
  'KetoGo',
  'KicksCrew',
  'Kiwi',
  'Kiwi US',
  'Klarna',
  'Klinio',
  'Korsit',
  'Kraken',
  'Ksubi',
  'Ksubi US',
  'Kylie Skin UK',
  'Kylie Skin US',
  'LEGOLAND California - Hotels',
  'LEGOLAND California - Tickets',
  'LEGOLAND Florida - Hotels',
  'LEGOLAND Florida - Tickets',
  'LEGOLAND New York - Tickets',
  'LU Hellofresh LU',
  'Le Creuset',
  'Leonardo',
  'Lethal Performance',
  'Liberty Home Guard LLC',
  'Liberty Home Guard LLC (CA)',
  'LipLab',
  'Living Spaces',
  'Loaded.com',
  'Louis Vuitton',
  'Luckyland Casino',
  'Luckyland Slots',
  'Lusha',
  'MADISON MARRIOTT 292',
  'MCR - Abilene TX Courtyard',
  'MCR - Abilene TX Residence Inn',
  'MCR - Albuquerque NM Residence Inn',
  'MCR - Alexandria LA Courtyard',
  'MCR - Allentown PA HGI',
  'MCR - Atlanta Downtown GA Aloft',
  'MCR - Austin Airport TX Residence Inn',
  'MCR - Austin Domain TX Fairfield',
  'MCR - Austin Parmer TX TownePlace',
  'MCR - Austin Round Rock TX Home2',
  'MCR - Baltimore BWI Homewood',
  'MCR - Beaufort SC HGI',
  'MCR - Bowling Green KY Hampton',
  'MCR - Brownsville TX Courtyard',
  'MCR - Carlisle PA Residence Inn',
  'MCR - Chambers Minneapolis MN',
  'MCR - Champaign IL HGI',
  'MCR - Champaign IL Homewood',
  'MCR - Charleston North SC Courtyard',
  'MCR - Charleston Summerville SC Home2',
  'MCR - Charlotte Concord NC Hampton',
  'MCR - Charlotte Matthews NC Hampton',
  'MCR - Charlotte Southpark NC Canopy',
  'MCR - Charlotte Southwest NC SpringHill',
  'MCR - Charlotte Steele Creek NC Hampton',
  'MCR - Cincinnati Loveland OH HGI',
  'MCR - Cincinnati Milford OH Homewood',
  'MCR - Cleveland Downtown OH HGI',
  'MCR - Columbus Dublin OH HGI',
  'MCR - Corpus Christi TX Courtyard',
  'MCR - Corpus Christi TX HGI',
  'MCR - Corpus Christi TX TownePlace',
  'MCR - Dallas Allen TX Homewood',
  'MCR - Dallas DFW Colleyville TX Hampton',
  'MCR - Dallas DFW Euless TX Home2',
  'MCR - Dallas DFW Euless TX Tru',
  'MCR - Dallas Grand Prairie TX Courtyard',
  'MCR - Dallas Plano TX Courtyard',
  'MCR - Dallas Plano TX Residence Inn',
  'MCR - Dallas Richardson TX HGI',
  'MCR - Daytona Oceanfront FL Hampton',
  'MCR - DeLand FL Courtyard',
  'MCR - Denver Englewood CO HGI',
  'MCR - Dunn NC Hampton',
  'MCR - El Paso Airport TX Fairfield',
  'MCR - El Paso Airport TX TownePlace',
  'MCR - FtWorth Downtown TX Fairfield',
  'MCR - FtWorth TCU Area TX TownePlace',
  'MCR - Glen Allen VA HGI',
  'MCR - Hampton VA HGI',
  'MCR - Hampton VA SpringHill',
  'MCR - Harrisburg Hershey PA TownePlace',
  'MCR - Houston Downtown TX Aloft',
  'MCR - Houston I10 Park Row TX Courtyard',
  'MCR - Houston I10 Park Row TX Hampton',
  'MCR - Houston IAH TX Fairfield',
  'MCR - Houston Woodlands TX TownePlace',
  'MCR - Huntsville AL TownePlace',
  'MCR - Indianapolis Northwest IN Hampton',
  'MCR - Indianapolis Northwest IN Residence Inn',
  'MCR - Jackson TN Courtyard',
  'MCR - Jacksonville Flagler Center FL Courtyard',
  'MCR - Jacksonville NC TownePlace',
  'MCR - Kansas City Leawood KS Aloft',
  'MCR - Kansas City Speedway KS Homewood',
  'MCR - Killeen TX Residence Inn',
  'MCR - King of Prussia PA Hampton',
  'MCR - Lake Mary FL Hampton',
  'MCR - Lexington Hotel NY',
  'MCR - Lima OH Courtyard',
  'MCR - Little Rock AR Homewood',
  'MCR - Louisville St Matthews Mall KY HGI',
  'MCR - Luxury Collection NYC',
  'MCR - Memphis Southaven MS Home2',
  'MCR - Miami MIA FL Hilton',
  'MCR - Midland TX HGI',
  'MCR - Midland TX Residence Inn',
  'MCR - Midland TX TownePlace',
  'MCR - Milwaukee Downtown WI Courtyard',
  'MCR - Minneapolis Downtown MN Doubletree',
  'MCR - Minneapolis University Area MN HGI',
  'MCR - Mt Prospect IL Hampton',
  'MCR - Nashville Smyrna TN Home2',
  'MCR - Nashville Smyrna TN Tru',
  'MCR - Newark Airport NJ Renaissance',
  'MCR - Newark Downtown NJ Courtyard',
  'MCR - Newport News VA Courtyard',
  'MCR - Norfolk VA Courtyard',
  'MCR - Norfolk VA Residence Inn',
  'MCR - Odessa TX Courtyard',
  'MCR - Odessa TX Homewood',
  'MCR - Odessa TX Residence Inn',
  'MCR - Orlando Lake Buena Vista FL Hyatt Place',
  'MCR - Orlando Sea World FL HGI',
  'MCR - Pasadena Hotel and Pool CA',
  'MCR - Peabody MA SpringHill',
  'MCR - Phoenix Avondale AZ HGI',
  'MCR - Phoenix Avondale AZ Homewood',
  'MCR - Phoenix Biltmore AZ Hampton',
  'MCR - Phoenix Chandler AZ Hilton',
  'MCR - Phoenix Tempe AZ SpringHill',
  'MCR - Phoenix Tempe AZ TownePlace',
  'MCR - Pompano Beach FL Residence Inn',
  'MCR - Pueblo CO Hampton',
  'MCR - Rogers AR Fairfield',
  'MCR - Royalton Hotel NYC',
  'MCR - San Antonio Downtown TX SpringHill',
  'MCR - San Antonio Northwest TX TownePlace',
  'MCR - Santa Fe NM Hampton',
  'MCR - Savannah Port Wentworth GA Hampton',
  'MCR - Seattle SeaTac Airport WA Residence Inn',
  'MCR - Seguin TX TownePlace',
  'MCR - Sheraton NYC Times Square',
  'MCR - Solomons MD HGI',
  'MCR - Spartanburg SC Residence Inn',
  'MCR - TWA Hotel JFK NYC',
  'MCR - Tallahassee FL DoubleTree',
  'MCR - Tallahassee FL Home2',
  'MCR - Temple TX Residence Inn',
  'MCR - The High Line Hotel NYC',
  'MCR - Toledo Perrysburg OH Hampton',
  'MCR - Troy AL Courtyard',
  'MCR - Troy AL Hampton',
  'MCR - Tucson AZ TownePlace',
  'MCR - Tulsa Bixby OK Hampton',
  'MCR - Warwick RI HGI',
  'MCR - Waukegan IL Hampton',
  'MCR - West Haven CT Hampton',
  'MCR - West Monroe LA HGI',
  'MCR - Yuma AZ Homewood',
  'MCR- Austin University TX Residence Inn',
  'MCR- Chattanooga TN Staybridge',
  'MCR- Chicago ORD IL Hyatt Regency',
  'MCR- Dallas DFW Grapevine TX Residence Inn',
  'MCR- Houston IAH TX TownePlace',
  'MCR- Miami MIA FL Hyatt Place',
  'MCR- Phoenix Airport North AZ HGI',
  'MOMA',
  'MR Goodchop US',
  'Madison Reed',
  'Mainstage',
  'Mako Moco',
  'MeetStart',
  'Mentorship',
  'Merlin Annual Pass',
  'Moon Active EU',
  'Moon Active UK',
  'Moon Active US',
  'Musement',
  'MyDiabetes',
  'Myhouse',
  'NL Hellofresh NL',
  'NL Marley Spoon',
  'NO Hellofresh NO',
  'NZ Hellofresh NZ',
  'Nixon AU',
  'NoCarbsChallenge',
  'Noleggiare',
  'Nordstrom',
  'NorthernTool',
  'Norwegian Cruise Line - Oceania Cruises - Regent Seven Seas Cruises',
  'Novelship',
  'Now TV',
  'Nuderie',
  'OleHenriksen',
  'Olivela',
  'Omio',
  'On Location',
  'OnBuy',
  'Out Of Network Rent',
  'Outcast Clothing',
  'Outlook Amusements, Inc',
  'Oxylabs',
  'PCProtect',
  "PPHE - Art'amsterdam Hotel",
  'PPHE - Art\'otel London Battersea Power Station',
  "PPHE - Art'otel London Hoxton",
  "PPHE - Art'otel Rome",
  'PPHE - Holmes Hotel',
  'PPHE - Park Plaza Amsterdam Airport Hotel',
  'PPHE - Park Plaza County Hall',
  'PPHE - Park Plaza Eindhoven',
  'PPHE - Park Plaza Leeds',
  'PPHE - Park Plaza London Park Royal',
  'PPHE - Park Plaza London Waterloo',
  'PPHE - Park Plaza Nottingham',
  'PPHE - Park Plaza Riverbank London',
  'PPHE - Park Plaza Victoria Amsterdam',
  'PPHE - Park Plaza Victoria London',
  'PPHE - Park Plaza Vondelpark Amsterdam',
  'PPHE - Park Plaza Westminster Bridge',
  'PVH CK',
  'PVH TH',
  'PacSun',
  'Passes Inc.',
  'Patreon',
  'Patrick Ta Beauty_#_e873840',
  'Payoneer',
  'Peacock',
  'PeopleFinders.com',
  'Peppa Pig Theme Park Dallas - Tickets',
  'Peppa Pig Theme Park Florida - Tickets',
  'PerfectBody',
  'PetSuppliesPlus',
  'Phoenix Scottsdale AZ Home2',
  'Plarium',
  'Play Perfect Ltd',
  'PlayerMaker',
  'Playtika',
  'Playtomic_Dubai',
  'Playtomic_US',
  'Priceline',
  'Psycho Bunny',
  'PumaMX',
  'Pura',
  'Pyramid - Cambria Hotel Pittsburgh Downtown',
  'Pyramid - Colorado Springs Marriott',
  'Pyramid - Courtyard by Marriott Pittsburgh North',
  'Pyramid - DoubleTree Boston',
  'Pyramid - DoubleTree Denver',
  'Pyramid - ELEO at the University of Florida',
  'Pyramid - Hilton Penns',
  'Pyramid - Renaissance Indianapolis North',
  'Pyramid - Residence Inn Boston Harbor on Tudor Wharf',
  'Pyramid - Residence Inn Cincinnati',
  'Pyramid - Rise Uptown',
  'Pyramid - Riverhouse Deschutes',
  'Pyramid - Spruce Point',
  'Pyramid - The Bradley Hotel',
  'Pyramid - The WigWam',
  'Pyramid - Wayfinder Waikiki',
  'Pyramid - Westin Tampa Bay',
  'Pyramid - Wyndham Boston',
  'Pyramid- Wayfinder Bishop',
  'RGG',
  'Ralph Lauren Inc.',
  'Ramp',
  'Ramp Swaps LLC',
  'RazerGold',
  'Reservation Day',
  'Reservation Stays',
  'Reset',
  'Resident Home',
  'Revice',
  'Riskified Hopper',
  'RobinsKitchen',
  'RocketReach',
  'SE Hellofresh SE',
  'SKIMS',
  'Sardine',
  'Scan Guard',
  'Schoffel',
  'ScholarshipOwl',
  'Scrapingbee.com',
  'SeatGeek',
  'Sephora',
  'SephoraAPAC',
  'Sherpa Adventure Gear',
  'Shoe Carnival',
  'Shop Simon',
  'Shop.com',
  'SimpleTire',
  'Size CA',
  'Sky Showtime',
  'Smartwool',
  'Sorare EU',
  'Spines - BOOX Publishing Technologies US Inc',
  'Spinzta',
  'Splitit - New',
  'Sportsman Guide',
  'Spotify Audiobooks',
  'Spotify For Artists',
  'Spotify Premium',
  'Stadium Goods',
  'Steady',
  'Stuart Weitzman',
  'StubHub International',
  'Sunbit',
  'Super Travel',
  'Super+',
  'Surfshark',
  'Survey Monkey',
  'Swingers',
  'SwyftX',
  'TGW',
  'TK Factor75 DK',
  'TO Factor75 BE',
  'TT Factor75 NL',
  'TV Factor75 SE',
  'TZ Factor75 DE',
  'Tailored Canvases',
  'Tango',
  'Tarte',
  'TeamViewer Germany GmbH',
  'Telfar',
  'The Joffrey Ballet',
  'The Level Group',
  'The London Eye - Tickets',
  'The Malachite Group',
  'The Money Factory LLC',
  'The North Face',
  'Thinkific Billing',
  'Thinkific Payments',
  'Thorpe Park - Tickets',
  'TicketNetwork',
  'Tickpick',
  'Timberland',
  'Timex',
  'TodayTix',
  'ToryBurch',
  'Total AV',
  'Total Adblock',
  'Total Cleaner',
  'Total Drive',
  'Total Password',
  'Total VPN',
  'Total WebShield',
  'Tractive GmbH',
  'Tractive Inc',
  'TractorSupply',
  'Travel Town',
  'Travlr',
  'Trimble Europe B.V.',
  'Trimble Inc',
  'Tripadvisor',
  'Trust My Travel ACI \u2013 Amstar Operaciones',
  'Tryplanetwash',
  'US Dinnerly',
  'US Hellofresh US',
  'US Marley Spoon',
  'Vans',
  'Velocity Festival',
  'Viagogo',
  'Viral Vault',
  'Viralgem Store_#_c2adc7b',
  'Vitalunahealth_#_14e1f18',
  'Voghion',
  'Wayfair',
  'Wegmans Groceries',
  'Wego',
  'Wellbots',
  'Wheely',
  'Wix.com',
  'Wolt FIN',
  'YE Youfoodz AU',
  'Yuzhen',
  'Z1 motorsports',
  'Zadig and Voltaire',
  'ZenBusiness Inc.',
  'ZeusX',
  'Zooplus',
  'bestbuy',
  'booksdeli.com_#_f2ca42f',
  'doordash',
  'doordash_us',
  'findhotel',
  'forter- hellofresh',
  'forter-findhotel',
  'forter-fiverr',
  'forter-skypicker',
  'forter-wish',
  'gemini',
  'honeybook',
  'iVisa',
  'joytunes',
  'lastminute',
  'melio',
  'paybis',
  'powtoon',
  'progressplay',
  'puls',
  'quientum_#_ec4ef6d',
  'usastoretesting_#_42256cb',
  'vcita',
  'zengaming',
];
