// ============================================================
// scopeOptions.js — Static option lists for scope dimension pickers
// ============================================================
// Replace placeholder values with the actual values from your
// Snowflake environment. These are used in the InputForm's
// "Customize Scope" section for multi-select filtering.
// ============================================================

export const REASON_GROUPS = [
  { value: 'fraud',     label: 'Fraud' },
  { value: 'non-fraud', label: 'Non-fraud' },
];

// ── PSP values ───────────────────────────────────────────────────────────────
export const PSP_OPTIONS = [
  'adyen',
  'airwallex',
  'amex',
  'bluesnap',
  'braintree',
  'chase',
  'checkout',
  'citi',
  'credorax',
  'dalenys',
  'discover',
  'dlocal',
  'ebanx',
  'ecommpay',
  'elavon',
  'elavon_connect',
  'elavon_payment_insider',
  'firstdata',
  'fiserv',
  'global_payments',
  'iyzico',
  'klarna',
  'kushki',
  'mangopay',
  'maverick',
  'merlink_drs',
  'moka',
  'nuvei',
  'omnipay',
  'payments_hub',
  'paypal',
  'paysafe',
  'payu',
  'sabadell',
  'shopify_payments',
  'square',
  'stripe',
  'tabapay',
  'vantiv',
  'worldpay',
  'worldpay_accertify',
  'worldpay_cb911',
  'worldpay_iq',
  'worldpay_mai',
  'worldpay_wdp',
  'zen',
  'unknown',
];

// ── Card scheme values ───────────────────────────────────────────────────────
export const CARD_SCHEME_OPTIONS = [
  'ach',
  'accel',
  'affirm',
  'afterpaytouch',
  'am',
  'american_express',
  'amex_amazopnay',
  'amex_googlepay',
  'amex_amazonpay',
  'apple_pay',
  'apple pay - maestro',
  'ax',
  'cabal debito',
  'cartes_bancaires',
  'cartebancaire',
  'cashapp',
  'ca',
  'clearpay',
  'codensa',
  'credit am',
  'cup',
  'debit/other',
  'debitcard',
  'diners',
  'diners club',
  'diners club international',
  'dinersclub',
  'directdebit_gb',
  'directebanking',
  'discover',
  'discover_googlepay',
  'ds',
  'eftpos_australia',
  'elo',
  'elo debit',
  'fawry',
  'ideal',
  'il',
  'interlink',
  'jcb',
  'jcb_applepay',
  'klarna',
  'link',
  'mada',
  'maestro',
  'maestro_usa',
  'maestro_usa_applepay',
  'mastercard',
  'mercadopago',
  'mr',
  'mt',
  'naranja',
  'nordea bank abp',
  'nyce',
  'nyce_applepay',
  'other',
  'paybybank',
  'paypal',
  'paywithgoogle',
  'pix',
  'prosa',
  'ps',
  'pulse',
  'riverty',
  's-pankki oy (s-bank limited)',
  'sepadirectdebit',
  'shazam',
  'star',
  'star_applepay',
  'troy',
  'troy debit',
  'twint',
  'unionpay',
  'upi',
  'unknown',
  'valuelink',
  'venmo',
  'verve',
  'vi',
  'visa',
  'vr',
  'turkiye is bankasi a.s.',
];

// ── Payment method values ────────────────────────────────────────────────────
export const PAYMENT_METHOD_OPTIONS = [
  '""',
  '1',
  '149',
  'accel',
  'ach',
  'advance deposit',
  'advance purchase',
  'ae',
  'affirm',
  'afterpay_clearpay',
  'afterpaytouch_au',
  'afterpaytouch_ca',
  'afterpaytouch_nz',
  'afterpaytouch_us',
  'am',
  'amazon_pay',
  'american express',
  'american_express',
  'american xpres',
  'amex ',
  'amex_amazonpay',
  'amx',
  'android_pay_card',
  'apple_pay',
  'automated',
  'card',
  'card reader',
  'card_present',
  'card_raw',
  'cardd',
  'cards',
  'cartebancaire',
  'cashapp',
  'cc',
  'checkout',
  'chip and pin',
  'clearpay',
  'clearpay_gb',
  'contactless chip',
  'credit_card',
  'cup',
  'dc',
  'debbit card',
  'debit_card',
  'di',
  'directebanking',
  'ed',
  'eftpos_australia',
  'el',
  'electron',
  'elo',
  'emv',
  'emv capture',
  'emv capute ',
  'emv captue',
  'emv capture ',
  'fw',
  'gift_card',
  'google_pay',
  'jcb',
  'klarna',
  'ld',
  'link',
  'maestro',
  'maestro_usa',
  'magnetic stripe',
  'manual',
  'md',
  'mobile & ecommerce',
  'network_token',
  'nj',
  'nyce',
  'offline',
  'online',
  'ot',
  'other',
  'pay pal',
  'pay psl',
  'paybybank',
  'paypal',
  'payrails_card',
  'pix',
  'prepaid',
  'prepaid card',
  'pulse',
  'pulse_pinless',
  'recurring',
  'regular',
  'revolut_pay',
  'riverty_at',
  'riverty_ch',
  'riverty_de',
  'riverty_nl',
  'star',
  'twint',
  'ui',
  'unknown',
  'us_bank_account',
  'vc',
  'vd',
  've',
  'venmo_account',
  'vi',
];
